apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: k8s
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=  # base64-encoded value of "admin"
  POSTGRES_PASSWORD: YWRtaW4xMjM=  # base64-encoded value of "admin123"
  POSTGRES_DB: bGlicmFyeV9kYg==  # base64-encoded value of "library_db"
